# Generated by Django 5.2.15 on 2026-06-03 15:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_pin', models.CharField(default='1234', max_length=4)),
                ('star_to_dollar_rate', models.PositiveIntegerField(default=2)),
                ('daily_star_limit', models.PositiveIntegerField(default=10)),
                ('theme', models.CharField(choices=[('sunny', 'Sunny Yellow'), ('sky', 'Sky Blue'), ('forest', 'Forest Green'), ('candy', 'Candy Pink')], default='sunny', max_length=20)),
                ('notifications_enabled', models.BooleanField(default=False)),
                ('daily_notification_hour', models.PositiveSmallIntegerField(default=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KidProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('avatar_emoji', models.CharField(default='⭐', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SavingsGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('image_emoji', models.CharField(blank=True, default='🎯', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_goals', to='starbank.kidprofile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StarAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_adjustments', to='starbank.kidprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('task_type', models.CharField(max_length=200)),
                ('stars', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'unique_together': {('user', 'task_type')},
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('spend', 'Spend'), ('save', 'Save'), ('invest', 'Invest'), ('charity', 'Charity')], max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='starbank.kidprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('task_type', models.CharField(max_length=200)),
                ('stars', models.PositiveIntegerField(default=1)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_tasks', to='starbank.kidprofile')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_instances', to='starbank.tasktemplate')),
            ],
            options={
                'ordering': ['completed_at', 'name'],
                'unique_together': {('kid', 'date', 'task_type')},
            },
        ),
    ]
